# Generated by Django 3.2.5 on 2021-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersfavourites',
            name='products',
        ),
        migrations.AddField(
            model_name='usersfavourites',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
